# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod properties
mod.name=Stonecutter Template
mod.id=template
mod.version=1.0
mod.group=btw.lowercase.template
mod.description=
mod.discord=

# Dependencies
deps.fabric_loader_version=0.18.4

deps.devauth_version=1.2.2

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_dep=[VERSIONED]
mod.mc_version=[VERSIONED]

# Versioned
deps.mappings_version=[VERSIONED]